#!/bin/bash

VERSION="5.32"
URL="http://www.jwz.org/xscreensaver/xscreensaver-${VERSION}.tar.gz"
DEST="${HOME}/xscreensaver-${VERSION}-build"
mkdir -p $DEST
pushd $DEST
if [ ! -f "xscreensaver-${VERSION}.tar.gz" ]; then
    if [ -x /usr/bin/wget ]; then
        wget $URL
    elif [ -x /usr/bin/curl ]; then
        curl -o "xscreensaver-${VERSION}.tar.gz" $URL
    else
        echo "need to download source but can't..."
        exit 1
    fi
fi
if [ ! -d "xscreensaver-${VERSION}" ]; then
    tar xfz "xscreensaver-${VERSION}.tar.gz"
fi
popd
#./shape_to_h  > commander.h
DEST=${DEST}/xscreensaver-${VERSION}
cp commander.{c,h,man} $DEST/hacks/glx
cp commander.xml $DEST/hacks/config
patch $DEST/hacks/glx/Makefile.in < Makefile.in.diff
cd $DEST
touch config.h
./configure
make
echo ""
if [ -x ${DEST}/hacks/glx/commander ]; then
    echo built: ${DEST}/hacks/glx/commander
else
    echo build failed... sorry
fi
