#!/bin/bash

VERSION="5.36"
URL="http://deb.debian.org/debian/pool/main/x/xscreensaver/xscreensaver_${VERSION}.orig.tar.gz"
DEST="${HOME}/xscreensaver-${VERSION}-build"

pushd ~
if [ ! -f "xscreensaver_${VERSION}.orig.tar.gz" ]; then
    if [ -x /usr/bin/wget ]; then
        wget $URL
    elif [ -x /usr/bin/curl ]; then
        curl -o "xscreensaver_${VERSION}.orig.tar.gz" $URL
    else
        echo "need to download source but can't..."
        exit 1
    fi
fi
mkdir -p $DEST
cd $DEST
if [ ! -d "xscreensaver-${VERSION}" ]; then
    tar xfz ~/xscreensaver_${VERSION}.orig.tar.gz
fi
popd
#./shape_to_h  > commander.h
DEST=${DEST}/xscreensaver-${VERSION}
cp commander.{c,h,man} $DEST/hacks/glx
cp commander.xml $DEST/hacks/config
patch $DEST/hacks/glx/Makefile.in < Makefile.in.diff
if [ $? -ne 0 ]; then
    echo "patching failed, aborting"
    exit 1
fi
cd $DEST
touch config.h
./configure
make
echo ""
if [ -x ${DEST}/hacks/glx/commander ]; then
    echo built: ${DEST}/hacks/glx/commander
else
    echo build failed... sorry
fi
