#!/usr/bin/perl
# vi:ai:ts=4:sw=4:cindent

use Data::Dumper;
use Math::Vec qw(NewVec); # libmath-vec-perl

open(I,"B7051600.TXT") or die "open failed: $!\n";

$first_colon=0;
$waiting_for_name=0;
$name="";
@ships=();
$exp_size=5; # size to map to

while(1) {
	skip_to_colon();
	$name=lc(r());
	next if $name=~m/splinter/i; # can't parse that one
	next if $name=~m/square/i; # boring
	next if $name=~m/tetra/i; # boring
	$bonusfaces=0;
	if($name eq "krait") { $bonusfaces=4; } # keep the side "aerials"(?)
	$front_laser=r(); # FIXME use this vertex number
	$qvf=r();
	($qv, $qf) = split(/,/, $qvf);
	if($qv=~m/([^-]+)-(\d+)/) { $qv=hex_to_dec($1)-$2; }
		else { $qv=hex_to_dec($qv); }
	if($qf=~m/([^-]+)-(\d+)/) { $qf=hex_to_dec($1)-$2; }
		else { $qf=hex_to_dec($qf); }
#	if($qf=~m/-/) { $qf=hex_to_dec($qf); } else { $qf=eval $qf; }
	push @ships, $name;
	$qf += $bonusfaces;
	print "\n/* ", $name, " has ", $qv, " vertices and ",
		  $qf, " faces */\n\n";
	$vertices=r(); # literal "vertices"
	if($vertices !~ m/vertices/i) { print "not vertices: $l\n"; exit; }
	$maxx=0; $maxy=0; $maxz=0;
	@verts=();
	print "GLfloat ", $name, "_v[] = {\n";
	for ($i=0; $i<$qv; $i++) {
		$l=r();
		($x,$y,$z) = split(/,/, $l);
		$x=hex_to_dec($x); $y=hex_to_dec($y); $z=hex_to_dec($z);
		if($x>$maxx) { $maxx=$x; }
		if($y>$maxy) { $maxy=$y; }
		if($z>$maxz) { $maxz=$z; }
		push @verts, ($x,$y,$z);
	}
	$max=0;
	if($maxx>$max) { $max=$maxx; }
	if($maxy>$max) { $max=$maxy; }
	if($maxz>$max) { $max=$maxz; }
	$scale=$exp_size/$max;
	print "/* scale=$scale */\n";
	for ($i=0; $i<$qv; $i++) {
		$x = $verts[$i*3];
		$y = $verts[$i*3 + 1];
		$z = $verts[$i*3 + 2];
		print "/* $x,$y,$z -> */ ";
		print $x*$scale, ",", $y*$scale, ",", $z*$scale, ",\n";
	}
	print "};\n";
	$faces=r(); # literal "faces"
	if($faces !~ m/faces/i) { print "not faces: $l\n"; exit; }
	print "GLint ", $name, "_f[] = {\n";
	@normals = ();
	for ($i=0; $i<$qf; $i++) {
		$l=r();
		($col,$nx,$ny,$nz,$rest) = split(/,/, $l, 5);
		$rest=fix_winding_order($rest);
		print $rest, ",\n";
	}
	print "0\n";
	print "};\n";
}

# not reached
exit(0);

# read a line, skipping REMs and stripping whitespace
sub r {
	my $r;
	do {
		$r=<I>;
		chomp $r;
		$r =~ s/^REM  kr1/ kr1/; # keep Krait aerials
		if($r =~ m/^REM/) { print "/* skipping: $r */\n"; }
	} until ($r !~ m/^REM/);
	$r=~s/^\s*//;
	$r=~s/\s*$//;
	return($r);
}

sub skip_to_colon {
	while(<I>) {
#print ">> ", $_;
		if(m/file ends/i) { trailer(); exit(0); }
		last if (m/^:/);
	}
}

sub hex_to_dec {
	my $h=shift;
	my $m="";
	if($h=~m/^-/) { $m="-"; $h=~s/^-//; }
	if($h!~m/^&/) { return($m.$h); }
	my $v=$h;
	$v=~tr/-&//d;
	return($m.hex($v));
}

sub trailer {
	print "char *ship_names[] = {\n";
	foreach $i (@ships) {
		print "\t\"", $i, "\",\n";
	}
	print "};\n";
	print "\n#define NUM_ELEM(x) (sizeof (x) / sizeof (*(x)))\n\n";
	print "GLfloat *ship_v[] = {\n";
	foreach $i (@ships) {
		print "\t&", $i, "_v[0],\n";
	}
	print "};\n";
	print "GLint *ship_f[] = {\n";
	foreach $i (@ships) {
		print "\t&", $i, "_f[0],\n";
	}
	print "};\n";
}

# given a polygon, correct the winding order if necessary
sub fix_winding_order {
	my $poly=shift;
	($num,$origver) = split(/,/, $poly, 2);
	if($num<3) { return($poly); }
	@ver=split(/,/, $origver);
	($p1,$p2,$p3,$rest) = split(/,/, $origver, 4);

# if the dot product of a normal to the plane of the polygon and a
# point in/on the polygon is >0 then the winding order needs to be
# reversed

	$v1=NewVec($verts[$p1*3], $verts[$p1*3+1], $verts[$p1*3+2]);
	$v2=NewVec($verts[$p2*3], $verts[$p2*3+1], $verts[$p2*3+2]);
	$v3=NewVec($verts[$p3*3], $verts[$p3*3+1], $verts[$p3*3+2]);

	$v12=NewVec($v2->Minus($v1));
	$v13=NewVec($v3->Minus($v1));

	$pun=NewVec($v1->PlaneUnitNormal($v12,$v13));
	$dp=$pun->Dot($v2);
	if($dp<0) { return('/* CW */ ' . $poly); }
	else { return("/* CCW $origver */ " .
			$num . ',' . join(',', reverse(@ver))) }
}
